### ISSUE TITLE
Support multiple levels of content nesting in learn site navigation

### ISSUE THREAD

**Issue by ajpiano** [jquery/jquery-wp-content#128]
the sidebar in the (learn.jquery.com child theme](https://github.com/jquery/web-base-template/blob/master/themes/learn.jquery.com/sidebar.php) needs to be updated to handle deeper hierarchies.

see also [grunt-jquery-content 25](https://github.com/jquery/grunt-jquery-content/issues/25)

**Comment by scottgonzalez** [comment]
This has been addressed enough for the current needs. Updates can happen without this issue remaining open.
