### ISSUE TITLE
API Sites: Better 404

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-wp-content#154]
PHP-style "you might have meant..."

**Comment by cassler** [comment]
I have a pretty good idea of how this could be snazzed up without too much overhead.

**Comment by gnarf** [comment]
Could we just add a wp_query / posts list to https://github.com/jquery/jquery-wp-content/blob/master/themes/jquery/404.php ??

We could use this on all the sites, not just API right?

**Comment by cassler** [comment]
@gnarf - Using for all sites might be a good base assumption for an approach. Specifically for API, we have some structure already:
- Serialize the results of various ```wp_query``` instances with ```post_count => -1```. There shouldn't be much need to do this query for every 404, just store the dataset in a single row in ```wp_options```. Probably want to do this as an action on  ```save_post```. 
- ```404.php``` then runs something like https://github.com/Glench/fuzzyset.js to compare the request against the stored data to display the best X matches or redirect if the confidence level is above a particular threshold.

Thoughts?

**Comment by cassler** [comment]
The same kind of process could be applied for any post type, taxonomy, category, etc based on request path. Example: /category/misspelledwerds would check against an array of known categories rather than posts and so forth.
