### ISSUE TITLE
Page navigation needs rethinking at 600px media-query.

### ISSUE THREAD

**Issue by kleinmaetschke** [jquery/jquery-wp-content#205]
At the 600px media-query level (iPad in various orientations), the navigation looks very disorienting.

![jQuery iPad nav example](http://iamkle.in/labs/misc/jqueryipadnav.jpg)

We need to address how to go about making the navigation/search area look nice at this mid-range screen size.

Personally, I feel it is too large for us to use the select button, but shrinking font-size on nav items on sites like jQueryUI leaves the nav items very small and almost illegible.

**Comment by Krinkle** [comment]
The opening screenshot from 2013 has apparently been deleted, but from what I can tell, the three breakpoints we have today for navigation (<480, <700, and beyond) all seem reasonable in how they use the available space. Shall we close this?

**Comment by mgol** [comment]
@Krinkle Sounds good to me, especially with your #452.
