### ISSUE TITLE
Forms: <input type=text> and <label> badly formatted

### ISSUE THREAD

**Issue by Skalman** [jquery/jquery-wp-content#221]
Using Firefox 21 on Ubuntu 12.10.

1. The text gets too little space in the inputs.
2. The <label> for "Comment" is weirdly positioned. Perhaps on its own line, like the others?

![blog jquery com - weird form](https://f.cloud.github.com/assets/138395/229045/31d996c4-8693-11e2-9f6b-048d30cb21d8.png)

**Comment by scottgonzalez** [comment]
This seems like it was fixed.
