### ISSUE TITLE
Warn on unsupported browsers

### ISSUE THREAD

**Issue by rxaviers** [jquery/jquery-wp-content#226]
Sites currently support:
- IE: >= 8
- Firefox and Chrome: current major X - 1 (X.y.z)
- Safari and Opera: current minor Y - 1 (x.Y.y)

For the browsers we have known-bugs at least, eg. IE<8 (known to be buggy and not supported on download builder), we could warn users like the example below:
![unspoported](https://f.cloud.github.com/assets/967155/308602/301e3560-96ec-11e2-801e-b5b9a0c125fe.png)

**Comment by arthurvr** [comment]
:+1: on this. Why not to link up something like http://browsehappy.com or http://outdatedbrowser.com? 

Could be done using conditional comments, but those wouldn't catch old versions of other browsers.

**Comment by scottgonzalez** [comment]
To be honest, we probably only care about catching old IE, if we really care about anything at all.

While we technically only support current - 1 for other browsers, in most cases even current - 10 will work just fine.

**Comment by mzgol** [comment]
I assume we'll be dropping IE8 compatibility with the release of jQuery 3.0.0; it would be bad if we couldn't upgrade to the latest version.

We could display a banner to IE<9 using conditional comments, I agree with @scottgonzalez that other browsers are not that important; the majority of old browsers visiting our sites will be old IE.

**Comment by arthurvr** [comment]
> I assume we'll be dropping IE8 compatibility with the release of jQuery 3.0.0; it would be bad if we couldn't upgrade to the latest version.

:+1:
