### ISSUE TITLE
Set up HD favicon for our sites.

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-wp-content#232]
@Krinkle:
> Most if not all sites only have 16x16 icons, they look crap on high-dpi displays (e.g. MacBook Pro with Retina display).

> I'd recommend we switch to making/serving multi-res ico files containing an array of 48x48, 32x32 and 16x16.

jquery/infrastructure#174

**Comment by Krinkle** [comment]
Bump. They're quite pixely for our growing number of HiDPI-enabled humans and non-humans. :crying_cat_face: 

![screen shot 2015-03-27 at 21 51 23](https://cloud.githubusercontent.com/assets/156867/6877707/70a2f750-d4cb-11e4-9525-9b9fd1e818bf.png)
