### ISSUE TITLE
OpenSearch description document

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-wp-content#236]
See jquery/api.jquery.com#65

**Comment by DawnPaladin** [comment]
No developer interest in this feature? I guess I can use the [Mycroft plugin](http://mycroftproject.com/search-engines.html?name=jquery).

**Comment by scottgonzalez** [comment]
> No developer interest in this feature?

Anyone interested in getting this working can send a pull request. Since that hasn't happened, I'm guessing there isn't much developer interest. At this point, I think we should just close this since it hasn't been deemed a priority by any of the teams. We'll still accept pull requests if someone wants to work on this.
