### ISSUE TITLE
jquery.com: Add high-res version of "Who's using jQuery"

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery-wp-content#250]
So they don't look pixelated on hidpi displays.

Also I believe the Wikipedia logo should be used with the name, not icon-only (like we do already for WordPress).

* http://wordpress.org/
  http://wordpress.org/about/logos/
  http://s.wordpress.org/about/images/logos/wordpress-logo-stacked-rgb.png
  <img src="http://s.wordpress.org/about/images/logos/wordpress-logo-stacked-rgb.png" title="WordPress logo" width="250"/>

* https://wikipedia.org/
  https://wikimediafoundation.org/wiki/Visual_identity_guidelines
  https://commons.wikimedia.org/wiki/File:Wikipedia-logo-v2-en.svg
  https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/500px-Wikipedia-logo-v2-en.svg.png
  https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/340px-Wikipedia-logo-v2-en.svg.png
  https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/170px-Wikipedia-logo-v2-en.svg.png
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/500px-Wikipedia-logo-v2-en.svg.png" title="Wikipedia logo" width="250"/>

* http://backbonejs.org/
  http://backbonejs.org/docs/images/backbone.png
  <img src="http://backbonejs.org/docs/images/backbone.png" title="Backbone.js logo" width="450"/>

* http://www.mediatemple.net/
  http://www.mediatemple.net/company/identity/
  http://www.mediatemple.net/_images/partnerlogos/mt-120x60-dk.png
  ![Media Temple logo](http://www.mediatemple.net/_images/partnerlogos/mt-120x60-dk.png)
  For hidpi we should probably scale down one of the larger versions?
  http://www.mediatemple.net/_images/partnerlogos/mt-250x140-dk.png
  <img src="http://www.mediatemple.net/_images/partnerlogos/mt-250x140-dk.png" width="125" title="Media Temple logo "/>

**Comment by scottgonzalez** [comment]
This section no longer exists.
