### ISSUE TITLE
Make meta description site specific

### ISSUE THREAD

**Issue by jzaefferer** [jquery/jquery-wp-content#261]
Currently all sites share this:

`<meta name="description" content="jQuery: The Write Less, Do More, JavaScript Library">`

We should have a description for each site, e.g. "QUnit: A JavaScript Unit Testing framework." for the QUnit sites, or "jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top of the jQuery JavaScript Library. Whether you're building highly interactive web applications or you just need to add a date picker to a form control, jQuery UI is the perfect choice." for the jQuery UI sites.

**Comment by gnarf** [comment]
cc @jquery/content - Would someone want to write a description for each site?  @scottgonzalez how were you planning on implementing this?

**Comment by arthurvr** [comment]
I can do that. Give me a few days.

**Comment by scottgonzalez** [comment]
We can just follow the pattern used by [`jq_logo_link()`](https://github.com/jquery/jquery-wp-content/blob/5ef7df7b68a732b28aec7015ca1f58d3e9e60af8/themes/jquery/functions.jquery.php#L170). Add the descriptions to `sites.php`, add a function to read the description from there, then update https://github.com/jquery/jquery-wp-content/blob/5ef7df7b68a732b28aec7015ca1f58d3e9e60af8/themes/jquery/header.php#L20 to call that function.
