### ISSUE TITLE
Replace wpmu_current_site() in sunrise.php

### ISSUE THREAD

**Issue by jzaefferer** [jquery/jquery-wp-content#303]
In `sunrise.php` we currently use `wpmu_current_site()`. This was deprecated in 3.9 with no replacement: https://core.trac.wordpress.org/ticket/27702

@nacin since you implemented that change, can you recommend a replacement or implement one? Thanks.

**Comment by aprillins** [comment]
@nacin I still got this when I use WordPress 3.9 and up (4.1). I just don't know how to solve this.
![gotthis](https://cloud.githubusercontent.com/assets/1317947/5823463/80557e56-a10f-11e4-8ebb-452e3a11789e.jpg)

**Comment by jzaefferer** [comment]
Yeah, I still get those, too.

**Comment by gnarf** [comment]
Ping @nacin - this isn't really blocking me from pushing infrastructure updates, but it is very unfortunate.

Any chance you can update this process for us or suggest someone who could help?

**Comment by nacin** [comment]
Hey all, sorry for never following up on this. I'm slammed through the end of the month but I asked @jeremyfelt (the WordPress multisite maintainer) if he has time to look. This should not be hard to fix -- stuff changed in 3.9 to make things better, and in the process broke my hack while also making it easier to do what I had originally tried to do. My work on jquery-wp-content specifically led to the work in core, so thank you for inspiring WP development!

**Comment by gnarf** [comment]
Fixed in 41db0b279c311e1421b00f6afb3fa4451f1e868e #379
