### ISSUE TITLE
Missing gradients in the learn.jquery.com CSS

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery-wp-content#335]
learn.jquery.com CSS includes many vendor prefixes for `linear-gradient` but it misses the most important form: the prefixless one. An example:
```css
	background-image: -webkit-gradient(linear, left top, left bottom, from(#ffea94), to(#FFEA5E)); 
	background-image: -webkit-linear-gradient(top, #ffea94, #FFEA5E); 
	background-image:    -moz-linear-gradient(top, #ffea94, #FFEA5E); 
	background-image:     -ms-linear-gradient(top, #ffea94, #FFEA5E); 
	background-image:      -o-linear-gradient(top, #ffea94, #FFEA5E); 
```
from: https://github.com/jquery/jquery-wp-content/blob/28fe8bd6d9447a598f7f3bf07352154c73cfbb97/themes/learn.jquery.com/style.css#L56-L60

By the way, Opera doesn't need a prefix since 12.10 (the last Presto version, current version is 26), Firefox from 16 (current version is 34); IE has never needed a prefix (only IE10 previews required one). The older WebKit gradient form also doesn't seem to be needed; the newer one is needed for the Android Browser. We only really need two forms IMO:
```css
	background-image: -webkit-linear-gradient(top, #ffea94, #FFEA5E); 
	background-image:         linear-gradient(to bottom, #ffea94, #FFEA5E); 
```

**Comment by arthurvr** [comment]
Other sites do this kind of things too. Not only with gradients btw, I'il assign this to me, I'm able to fix it shortly.

This was also the reason why I wanted to re-open https://github.com/jquery/jquery-wp-content/issues/66.
