### ISSUE TITLE
 Search at api.jquery.com gives inaccurate results.

### ISSUE THREAD

**Issue by KseniyaLight** [jquery/jquery-wp-content#359]
Search at api.jquery.com gives inaccurate results.

For example I searched "on" to get ".on()" function docs, but find it at end of results.

I speak with arthurvr about this.
He tell: Yeah. I do agree with you. We should probably give the entry title priority in the search results.

**Comment by arthurvr** [comment]
Yeah. Our search results on the API sites (not only api.jquery.com) are kinda inaccurate to say the least.

**Comment by dmethvin** [comment]
It would be nice if the search gave priority to the API name matches, so that a search for "wrap" would put those APIs at the top rather than the bottom. Either that or we should stop using the word "wrap" so much everywhere else. :smile:

**Comment by PaulAnnekov** [comment]
Will try to make pull request with fix tomorrow. Bug is [here](https://github.com/jquery/jquery-wp-content/blob/master/mu-plugins/api-sites/search-weights.php#L10) (not `search_term`, but `search_terms`)  and [here](https://github.com/jquery/jquery-wp-content/blob/master/mu-plugins/api-sites/search-weights.php#L19) (post_title is `on()`, but search term is just `on`, they are not equal and will not match).

**Comment by jzaefferer** [comment]
Nice job tracking those down!

**Comment by PaulAnnekov** [comment]
I have made some investigation and found that [Relevanssi](https://wordpress.org/plugins/relevanssi/) plugin for WordPress is really great. Here are some results:

'on'
![on](https://cloud.githubusercontent.com/assets/1203892/7112550/663a1392-e1d3-11e4-9387-563e7ca1d9d5.png)

'wrap html'
![wrap](https://cloud.githubusercontent.com/assets/1203892/7112552/697870b2-e1d3-11e4-99e2-dec1d715878e.png)

'wrap html' with search terms highlighting enabled
![wrap_highlight](https://cloud.githubusercontent.com/assets/1203892/7112553/6bc972c6-e1d3-11e4-90eb-414deebd3177.png)

**Comment by PaulAnnekov** [comment]
Of course, I can made our own 'relevant search' but I prefer ready-made solutions. 

What do you think? Maybe we should just add this plugin?

**Comment by scottgonzalez** [comment]
Using Relevanssi sounds fine to me. You can just include it in `mu-plugins` so we'll get it on every site.

**Comment by MartinMuzatko** [comment]
Any updates to this?  Using the API search is a pain in the ass.

**Comment by mgol** [comment]
@MartinMuzatko not yet. PRs improving the situation are welcome (e.g. using the plugin mentioned above).

**Comment by PaulAnnekov** [comment]
@mgol PR which is using the plugin above was submitted 2 years ago (https://github.com/jquery/jquery-wp-content/pull/361), but repo owners still can't find time to merge it :).

**Comment by mgol** [comment]
I'd appreciate a final review of #408 (which is @PaulAnnekov's PR rebased). If that's OK, I'll land it.

**Comment by mgol** [comment]
The PR rebased & landed, thanks @PaulAnnekov!

I've started testing it on stage before pushing to production and while at http://stage.api.jquery.com/?s=on I see `.on()` as the first entry, at the HTTPS version, i.e. https://stage.api.jquery.com/?s=on the results are different (way worse). Any idea what may differ between those two setups? cc @dmethvin

**Comment by mgol** [comment]
@dmethvin @Krinkle This looks great to me at first sight at https://stage.api.jquery.com/. Do you think it's OK to go to production now?

**Comment by dmethvin** [comment]
The search results look really good to me! Yeah let's give it a try.

**Comment by mgol** [comment]
I released it. I've noticed one regression immediately after releasing: pagination seems broken; the second & subsequent pages return the same results as the first one.

I still think it's way less broken than it was (who goes to the second page of search results after all?) but we should look into it.

It seems to me that all results are contained on one page...

**Comment by dmethvin** [comment]
Yes, it does look like all the results are on one page, which is probably why a common word like `on` makes the page take so long to render.  Pagination is mentioned in [a knowledge base article](https://www.relevanssi.com/knowledge-base/posts-per-page/) and I don't see that variable set in the `init.php` so maybe it's that simple?

**Comment by mgol** [comment]
For posterity: the pagination issue was resolved in PR #410 by @PaulAnnekov.
