### ISSUE TITLE
Upgrade to jQuery 3

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-wp-content#400]
Currently our sites use jQuery 1.11.3. We should switch to jQuery 3 (eating our own dogfood etc.).

cc @dmethvin @timmywil 

Note that this doesn't apply to examples on various API sites which have jQuery copies versioned in repositories specific to those sites.

**Comment by mgol** [comment]
jQuery is loaded here in the theme: https://github.com/jquery/jquery-wp-content/blob/f521f946394b6c0ad150ede3684c2f67bfb53b7b/themes/jquery/header.php#L31

**Comment by timmywil** [comment]
Thanks. I didn't notice that, but I agree we can kill the site.

**Comment by mgol** [comment]
The history site can be quite interesting. It stopped getting updated in 2014 and many links are dead and would have to be rewritten with Web Archive but still.

**Comment by timmywil** [comment]
I think if we wanted a page like that, we should just redo it static. As it's been broken for a while and not updated, I'd like to redirect and maybe add a history page later.

**Comment by timmywil** [comment]
All sites pass locally. The pages in demos and examples are loaded in iframes and have their own versions of jquery. I'm fairly confident we don't need to parameterize.

**Comment by mgol** [comment]
Good to hear!

**Comment by timmywil** [comment]
I would like to point out that whatever theme the blogs are loading has an even older version of jQuery than jquery-wp-content. That could also be upgraded, but I'd need to be pointed to where those themes are.

**Comment by timmywil** [comment]
Nevermind, I think I found it https://github.com/jquery/blog.jquery.com-theme

**Comment by timmywil** [comment]
I've run through all the staging sites and they look good to go. The only one I couldn't view was http://stage.jquerymobile.com. It's showing a 500 "Error establishing a database connection".
