### ISSUE TITLE
jQuery Mobile site has suddenly lost it's icons

### ISSUE THREAD

**Issue by ourson66** [jquery/jquery-wp-content#407]
at the following url:  http://api.jquerymobile.com/icons/

As of Oct 21, 2017, the icons have all disappeared - it looks like a problem with the CSS for the site, as it uses JQueryMobile's own styling for the appearance of these icons.

![image](https://user-images.githubusercontent.com/10282917/31854141-e19accc8-b662-11e7-9cb1-2c40b9cc94e8.png)

This is quite recent, as I was viewing this page Oct 19th, and they were fine.  I have refreshed and removed cache and refreshed, the problem persists.

**Comment by mgol** [comment]
cc @arschmitz

**Comment by Krinkle** [comment]
Comparing api.jquerymobile.com/icons/ via archive.org to [9 Oct 2017](http://web.archive.org/web/20171009203913/https://api.jquerymobile.com/icons/). Indeed it worked fine there. Looks like it was caused by the 1.5.0 upgrade, and some attributes weren't updated in this demo yet.

Fixed now!
