### ISSUE TITLE
Create an easy way to work on just web-base-template

### ISSUE THREAD

**Issue by ajpiano** [jquery/jquery-wp-content#42]
It would facilitate the process of working on HTML and CSS greatly if people don't have to clone each site project and grunt deploy it to their local environment. We should provide a sql dump they can quickly execute to populate their local install so they can get down to pixels.

**Comment by scottgonzalez** [comment]
This hasn't really gotten any attention in the past few years. I'm going to close this, but if someone wants to actually figure out a good solution and implement it, we can certainly restart discussions.
