### ISSUE TITLE
Plugins: Upgrade VaultPress to 2.1.4

### ISSUE THREAD

**Issue by hareesh-pillai** [jquery/jquery-wp-content#426]
The VaultPress plugin used in the site has to be updated to the latest version. 
The current version in the [WordPress plugins repository](https://wordpress.org/plugins/vaultpress/) is v2.1.4

Related: [Plugins: Upgrade VaultPress to 1.5.1](https://github.com/jquery/jquery-wp-content/commit/d1ae7251d6a872e780af292edb48eb5f1d258ef6)

**Comment by supertassu** [comment]
We dropped the plugin entirely in a76f40c.
