### ISSUE TITLE
Improve font-loading performance (avoid Typekit JS)

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery-wp-content#446]
Instead of using Adobe Typekit JS, perhaps we can load a bundle one or two font-files directly and load using CSS `@font-face`.

**Comment by Krinkle** [comment]
It seems this isn't possible with the current font family.

Klavika is not released under the SIL Open Font License, not under any other free software license. This is probably among the reason that it isn't available through Google Fonts either. It is exclusive to Adobe Typekit.

The official page for this font says at https://fonts.adobe.com/fonts/klavika#licensing-section:

>  purchase additional licensing and services [for] […]:
> * Self Hosting: Host web font files on your own server

And the general license FAQ from Adobe says at And https://helpx.adobe.com/fonts/using/font-licensing.html#web-host:

> **Can I host the web font files on my own server?**
>
> No. Adobe doesn't offer the ability to locally host fonts. Our web font hosting delivers fonts from a globally-distributed content delivery network (CDN), which performs much better and is more scalable than using local hosting for static assets.

Putting the blatant misinformation in their justification aside, the bottom line is that the license doesn't permit self-hosting. Given the otherwise free and unlimited distribution they permit, this might hint at some kind of "[you pay us with your data](https://en.wikipedia.org/wiki/You_are_the_product)" underneath it. But either way, we cannot self-host this font as a way to improve privacy and performance.

**Comment by timmywil** [comment]
I searched around on some sites that recommend fonts similar to Klavika, but I don't think any of them were as close as Cairo.
